const SKIN=
[
    {
        "name":"Default",
        "file":"default",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"DJ 155-Chan",
        "file":"dj_155chan",
        "author":"by Bolternon",
        "category":"fanmade"
    },
    {
        "name":"Herobrine",
        "file":"herobrine",
        "author":"by Cheatosphere64",
        "category":"fanmade"
    },
    {
        "name":"Saltsven",
        "file":"saltsven",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Zombie",
        "file":"zombie",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Collosal",
        "file":"collosal",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Glassed",
        "file":"glassed",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot0",
        "file":"botchar0",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot1",
        "file":"botchar1",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot2",
        "file":"botchar2",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot3",
        "file":"botchar3",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot4",
        "file":"botchar4",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot5",
        "file":"botchar5",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot6",
        "file":"botchar6",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot7",
        "file":"botchar7",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot8",
        "file":"botchar8",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot9",
        "file":"botchar9",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot10",
        "file":"botchar10",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot11",
        "file":"botchar11",
        "author":"(Official)",
        "category":"official"
    },
    {
        "name":"Bot12",
        "file":"botchar12",
        "author":"(Official)",
        "category":"official"
    },
];