const splash = [
    "Yes!",
    "A Brave New Look!",
    "100% pure!",
    "Made on Java!",
    "Better than Quake!",
    "More cubes!",
    "Knows where you live!",
    "Mine deep. This you will not smelt.",
    "...",
    "",
    "Your personal storyteller!",
    "Creepin' Creepy Creepers",
    "o diable...",
    "Will replace arcades!",
    "Highly Responsive to Players!",
    ":wq",
    "Paul Minetreides",
    "Thou shalt pass!",
    "Mine & Craft",
    "Order of the Rock",
    "Set in the world of Rubydung!",
    ".... . .-.. .-.. --- -.-.--",
    "Mind over Matter!",
    "Could be a Roguelike!",
    "Oh, Shiny!",
    "From the Secret Garden of the Shrine!",
    "Heroes, Heroines, Celestial Warriors!",
    "A Block In Which A Creeper Lives And Gnaws!",
    "One Ore to Rule them All.",
    "It's Quality of Life We're talking about here!",
    "How?",
    "Block Sabbath",
    "I teleported bread!",
    "<(*_*)>",
    "Made with some foreign characters",
    "*Blows up pancakes with mind*",
    "Cyclone!",
    "Don't go into the woods at night!",
    "Fastest thing alive!",
    "Doesn't exist!",
    "An ultimate weapon!",
    "You're going into orbit!",
    "Not on the radio!",
    "You can be a saint!",
    "Holding onto anything at the end of everything!",
    "Send us your floppy!",
    "Not your relative \"Chin\"!",
    "Everything sucks forever!",
    "I want 5 character = 1000$",
    "Hello, Risugami!",
    "Smooth jazz!",
    "Pianos are nice.",
    "*steals your diamonds and leaves*",
    "One sandwich coming up!",
    "Why?-... Why are there...",
    "Ailuride roam your location.",
    "Send the squids!",
    "Good morning!",
    "We hope you're doing alright.",
    "golf",
    "Surplus to Requirement.",
    "OMELETTE.EXE"
];
function s() {
    document.querySelector(".spl").innerHTML = splash[Math.floor(Math.random() * splash.length)];
    if (profile.username != "") document.querySelector(".pro").innerHTML = profile.username;
};